name: build.web.v1
on:
  workflow_call:
    inputs:
      APP_NAME:
        description: "App name"
        required: true
        type: string
      APP_DOCKER_REPOSITORIES:
        description: "Docker repositories name"
        required: true
        type: string
      GCP_PROJECT:
        description: "GCP project"
        required: true
        type: string
      ZMODE:
        description: "Mode name [dev, prod, ...]"
        required: false
        type: string
        default: dev
      NODE_RUN_SCRIPT:
        description: "Nodejs run script"
        required: false
        type: string
        default: "build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate with GitHub package registry
        run: |
          echo "machine github.com login lctech-zeki password ${{ secrets.CI_TOKEN }}" >> ~/.netrc
          git config --global url."https://${{ secrets.CI_TOKEN }}:x-oauth-basic@github.com/lctech-lucy".insteadOf "https://github.com/lctech-lucy"
          rm -rf .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.CI_TOKEN }}" >> .npmrc 
          echo "@lctech-tw:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "@lctech-lucy:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: ⚙️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SA_KEY_GITHUB_CI}}
      - name: ⚙️ Setting docker auth
        run: gcloud auth configure-docker -q && gcloud auth configure-docker $(echo ${{inputs.APP_DOCKER_REPOSITORIES}}  | cut -d "/" -f 1) -q
      - name: ⚙️ Set up Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: ⚙️ Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: ⚙️ Build Nodejs
        run: pnpm i && rm -rf ~/.netrc .npmrc && .env.${{inputs.ZMODE}} .env && pnpm run ${{inputs.NODE_RUN_SCRIPT}}
      - name: ⛴ Set up Docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: ⛴ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: ⛴ Docker build / tag / push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
          file: .github/docker/Dockerfile
          tags: |
            ${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:latest
            ${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:${{github.sha}}
            ${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:${{inputs.ZMODE}}-latest
            ${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:${{inputs.ZMODE}}-${{github.run_number}}
            ${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:${{github.ref_name}}-${{github.run_number}}
