name: Cloud Deploy

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: false

jobs:
  deploy:
    permissions:
        id-token: write
        contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: git config --global url."https://${{ secrets.CI_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - uses: lctech-tw/dci-action@v0
        name: dci-action
        with:
          wif_provider_name: ${{ secrets.WIF_PROVIDER_NAME }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          project_id: ${{ secrets.PROJECT_ID }}
