name: deploy.cloudrun.grpc.v1
on:
  workflow_call:
    inputs:
      ZMODE:
        description: "mode"
        required: false
        type: string
        default: dev
      APP_DOCKER_REPOSITORIES:
        description: "Docker repositories name"
        required: true
        type: string
      APP_NAME:
        description: "App name"
        required: true
        type: string
      GCP_PROJECT:
        description: "GCP project"
        required: true
        type: string
      GCP_CLOUD_RUN_NAME:
        description: "GCP cloudrun name"
        required: true
        type: string
      GCP_CLOUD_RUN_REGION:
        description: "GCP cloudrun zone"
        required: true
        type: string
      GCP_CLOUD_RUN_DEPLOY_GRPC_WEB:
        required: true
        type: boolean
      GCP_CLOUD_RUN_PORT_GRPC_WEB:
        required: false
        type: string
      GCP_CLOUD_RUN_PORT_GRPC:
        required: true
        type: string
      GCP_CLOUD_RUN_VPC:
        required: false
        type: string
      GCP_CLOUD_RUN_CPU:
        required: false
        type: string
        default: "1"
      GCP_CLOUD_RUN_MEM:
        required: false
        type: string
        default: "1Gi"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⚙️ Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SA_KEY_GITHUB_CI}}
      - name: Deploy
        run: |
          echo "@ deploy : $GCP_PROJECT -> $GCP_CLOUD_RUN_NAME -> $ZMODE"
          if [ ${{inputs.GCP_CLOUD_RUN_DEPLOY_GRPC_WEB}} ];then
            echo "@ Deploy gRPC Web"
            gcloud run deploy ${{inputs.GCP_CLOUD_RUN_NAME}}-grpc-web \
              --project ${{inputs.GCP_PROJECT}}  \
              --region ${{inputs.GCP_CLOUD_RUN_REGION}} \
              --image "${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:${{inputs.ZMODE}}-${{github.run_number}} \            
              --cpu "${{inputs.GCP_CLOUD_RUN_CPU}}" \
              --memory "${{inputs.GCP_CLOUD_RUN_MEM}}" \
              --port "${{inputs.GCP_CLOUD_RUN_PORT_GRPC_WEB}}" \
              --vpc-connector "${{inputs.GCP_CLOUD_RUN_VPC}}" \
              --env-vars-file ./.github/config/$ZMODE.yaml \
              --ingress internal-and-cloud-load-balancing &
          fi
          echo "@ Deploy gRPC"
          gcloud run deploy ${{inputs.GCP_CLOUD_RUN_NAME}}-grpc \
            --project ${{inputs.GCP_PROJECT}}  \
            --region ${{inputs.GCP_CLOUD_RUN_REGION}} \
            --image "${{inputs.APP_DOCKER_REPOSITORIES}}/${{inputs.APP_NAME}}:${{inputs.ZMODE}}-${{github.run_number}} \            
            --cpu "${{inputs.GCP_CLOUD_RUN_CPU}}" \
            --memory "${{inputs.GCP_CLOUD_RUN_MEM}}" \
            --port "${{inputs.GCP_CLOUD_RUN_PORT_GRPC}}" \
            --vpc-connector "${{inputs.GCP_CLOUD_RUN_VPC}}" \
            --env-vars-file ./.github/config/$ZMODE.yaml \
            --ingress internal-and-cloud-load-balancing
