name: testing.golang.v1
on:
  workflow_call:
    inputs:
      DB_TABLE_NAME:
        description: "DB table name"
        required: true
        type: string
      GO_BUILD_PATH:
        description: "File [main.go] path"
        required: false
        type: string
        default: "./cmd/server/"
      PRE_TEST_SCRIPT_PATH:
        description: "Pre test script path"
        required: false
        type: string
        default: "./.github/testing"
      PRE_TEST_SCRIPT_FILE:
        description: "Pre test script file"
        required: false
        type: string
        default: "psql-init.sh"
      TEST_COVERAGE_PATH:
        description: "Test coverage path for go test command"
        required: true
        type: string
        default: "./transport/...,./internal/service,./internal/repo"
      TEST_MAIN_PATH:
        description: "Test path for go test command"
        required: true
        type: string
        default: "./test/integration"
      TEST_COVERAGE_THRESHOLD:
        description: "Test coverage threshold percentage"
        required: false
        type: number
        default: 70
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
      - name: 🔍 Run Go security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ⚙️ Obtain GitHub App Installation Access Token
        id: githubAppAuth
        run: |
          TOKEN=$(npx obtain-github-app-installation-access-token ci ${{secrets.GH_APP_CREDENTIALS_TOKEN}})
          echo "::add-mask::$TOKEN" && echo "::set-output name=token::$TOKEN"
      - name: ⚙️ Setting GitHub Auth
        run: git config --global url."https://oauth2:$GITHUB_TOKEN@github.com/lctech-tw".insteadOf "https://github.com/lctech-tw"
        env:
          GITHUB_TOKEN: ${{steps.githubAppAuth.outputs.token}}
      - name: ⚙️ Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - name: ⚙️ Init db server
        run: |
          docker run -it --rm -p 6379:6379 redis &
          docker run --rm --name psql \
                      -p 5432:5432 \
                      -e POSTGRES_USER=postgres \
                      -e POSTGRES_PASSWORD=12345678 \
                      -e POSTGRES_DB=${{inputs.DB_TABLE_NAME}} \
                      -e POSTGRES_ENCODING=UTF8 \
                      -e POSTGRES_LC_ALL=en_US.UTF-8 \
                      -v ${{inputs.PRE_TEST_SCRIPT_PATH}}/:/test/ \
                      -d postgres &
          until PGPASSWORD=12345678 psql -U postgres -h 127.0.0.1 -p 5432 -w &>/dev/null
          do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
          docker exec -t psql bash /test/${{inputs.PRE_TEST_SCRIPT_FILE}} &
      - name: ⚙️ Build Golang / Run Tests
        run: |
          cd ${{inputs.GO_BUILD_PATH}} && go build . && cd -
          go mod vendor
          go test -cover -coverpkg "${{inputs.TEST_COVERAGE_PATH}}" "${{inputs.TEST_MAIN_PATH}}" -coverprofile=coverage.out
          go tool cover -func coverage.out
      - name: 🛡️ Quality Gate - Test coverage shall be above threshold
        env:
          TEST_COVERAGE_THRESHOLD: ${{inputs.TEST_COVERAGE_THRESHOLD}}
        run: |
          echo "品質門檻：檢查測試覆蓋率是否高於門檻 ..."
          echo "門檻值             : $TEST_COVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "目前測試覆蓋率     : $totalCoverage %"
          if (( $(echo "$totalCoverage $TEST_COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
            echo "通過"
          else
            echo "目前測試覆蓋率低於門檻，請增加單元測試或調低門檻值。"
            echo "未通過"
            exit 1
          fi
